# configs/default.yaml
data:
  counts_file: 'data/151673/RNA_counts.tsv'
  coor_file: 'data/151673/position.tsv'
  used_barcodes_file: 'data/151673/used_barcodes.txt'
model:
  alpha: 0.5  # 修正：原值 0.0001 过小，建议 0.1~0.9
  n_top_genes: 3000
  hidden_dims: [512, 30]
  rad_cutoff: 50
  k_neighbors: 6
  similarity_metric: "cosine"
train:
  n_epochs: 10
  lr: 0.0001
  weight_decay: 0.0001
  lambda_spatial: 0.1
  key_added: "GATES"
cluster:
  resolution: 1.0
output:
  spatial_plot_path: "results/spatial_plot.png"
  neighbor_stats_plot: 'figure/alpha{alpha}_{resolution}_Stereo-seq_Mouse_NumberOfNeighbors.png'
  spatial_plot_crop: null
