# 数据路径配置
data:
  counts_file: "E:/论文/空转第一篇/月底项目/数据集/Stereo-seq_MoB/RNA_counts.tsv"
  coor_file: "E:/论文/空转第一篇/月底项目/数据集/Stereo-seq_MoB/position.tsv"
  used_barcodes_file: "E:/论文/空转第一篇/月底项目/数据集/Stereo-seq_MoB/used_barcodes.txt"

# 模型与训练超参数
model:
  alpha: 0.0001 # 平衡空间网络和基因相似性网络的权重
  n_top_genes: 3000 # 用于分析的高变基因数量
  hidden_dims: [512, 30] # 编码器隐藏层维度
  rad_cutoff: 50 # 构建空间网络的半径阈值
  k_neighbors: 6 # 构建基因相似性网络的邻居数
  similarity_metric: "cosine" # 基因相似性度量: cosine, euclidean, pearson

# 训练参数
train:
  n_epochs: 1000
  lr: 0.0001
  weight_decay: 0.0001
  key_added: "GATES" # 嵌入结果在adata中的存储键名

# 聚类参数
cluster:
  resolution: 1.0 # Louvain聚类分辨率

# 可视化输出路径
output:
  neighbor_stats_plot: "E:/论文/空转第一篇/月底项目/数据集/Stereo-seq_MoB/figure/alpha{alpha}_{resolution}_Stereo-seq_Mouse_NumberOfNeighbors.png"
  spatial_plot_crop: [10100, 10721, 13810, 13093] # 裁剪坐标 [x_min, x_max, y_min, y_max]
